version: '3.8'

services:
  app:
    image: sanantino/cogenist_backend:latest  # Update with your Docker Hub username
    ports:
      - "5000:5000"  # API Port
      - "5001:5001"  # WebSocket Port
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - HOSTNAME=${HOSTNAME}
      - SQL_HOST=${SQL_HOST}  # Your AWS RDS Endpoint
      - SQL_PORT=${SQL_PORT}  # Usually 3306
      - SQL_USERNAME=${SQL_USERNAME}  # MySQL Username
      - SQL_PASSWORD=${SQL_PASSWORD}  # MySQL Password
      - SQL_DATABASE=${SQL_DATABASE}  # Database Name
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network
    command: npm run start:prod

  redis:
    image: redis:6.2
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: redis-server --requirepass "$REDIS_PASSWORD" --maxmemory 100mb --maxmemory-policy allkeys-lru
    env_file:
      - .env
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
